tool.smh_offsetter.name=Offsetter
tool.smh_offsetter.desc=Offset an animated entity to an origin
tool.smh_offsetter.0=Select the source entity to offset
tool.smh_offsetter.1=Select an offsetter, or select the source again to create one below it
tool.smh_offsetter.left=Offset an entity
tool.smh_offsetter.right=N/A
tool.smh_offsetter.reload=Remove a hologram (the entity following the offsetter)
tool.smh_offsetter.left_1=Select an offsetter, or select the source again to create one below it
tool.smh_offsetter.list_offsetter=Offsetter
tool.smh_offsetter.list_source=Source
tool.smh_offsetter.list_hologram=Hologram
tool.smh_offsetter.removed=Removed
tool.smh_offsetter.refresh=Refresh sources
tool.smh_offsetter.recapture=Recapture selected zero point
