tool.smh_offsetter.name=Offsetter
tool.smh_offsetter.desc=Offset an animated entity to an origin
tool.smh_offsetter.0=Select the source entity to offset
tool.smh_offsetter.1=Select an offsetter, or select the source again to create one below it
tool.smh_offsetter.left=Select the source entity to offset
tool.smh_offsetter.right=N/A
tool.smh_offsetter.reload=Remove a hologram (the entity following the offsetter)
tool.smh_offsetter.left_1=Select an offsetter, or select the source again to create one below it
tool.smh_offsetter.help1=Select offsetter-source-hologram trio in the list below, and then click the buttons below to interact with them 
tool.smh_offsetter.list_offsetter=Offsetter
tool.smh_offsetter.list_source=Source
tool.smh_offsetter.list_hologram=Hologram
tool.smh_offsetter.removed=Removed
tool.smh_offsetter.refresh=Refresh sources
tool.smh_offsetter.refresh.tooltip=Refresh the list of linked offsetters, sources, and holograms.
tool.smh_offsetter.recapture=Recapture selected zero point
tool.smh_offsetter.recapture.tooltip=Update the selected pair's zero point to its current positions.
tool.smh_offsetter.unlink=Unlink selected hologram
tool.smh_offsetter.unlink.tooltip=Remove the selected link without deleting its entities.
